syntax = "proto3";

package product;
option go_package = "github.com/wypwzc/go-mall/apps/product/pb;productpb";

message Product {
  int64 id = 1;
  string name = 2;
  string description = 3;
  int64 price_cents = 4;
  string image_url = 5;
  bool active = 6;
}

message ListProductsRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message ListProductsResponse {
  repeated Product items = 1;
  int64 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}

message GetProductRequest {
  int64 product_id = 1;
}

service ProductService {
  rpc ListProducts(ListProductsRequest) returns (ListProductsResponse);
  rpc GetProduct(GetProductRequest) returns (Product);
}
