// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: apps/stock/stock.proto

package stockpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_apps_stock_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stock_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_apps_stock_stock_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Available     int64                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_apps_stock_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stock_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_apps_stock_stock_proto_rawDescGZIP(), []int{1}
}

func (x *Stock) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Stock) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_apps_stock_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stock_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_apps_stock_stock_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveStockRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_apps_stock_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stock_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_apps_stock_stock_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reserved      bool                   `protobuf:"varint,2,opt,name=reserved,proto3" json:"reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_apps_stock_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stock_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_apps_stock_stock_proto_rawDescGZIP(), []int{4}
}

func (x *Reservation) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Reservation) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

var File_apps_stock_stock_proto protoreflect.FileDescriptor

const file_apps_stock_stock_proto_rawDesc = "" +
	"\n" +
	"\x16apps/stock/stock.proto\x12\x05stock\"0\n" +
	"\x0fGetStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"D\n" +
	"\x05Stock\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x03R\tavailable\"k\n" +
	"\x13ReserveStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"0\n" +
	"\x13ReleaseStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"D\n" +
	"\vReservation\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1a\n" +
	"\breserved\x18\x02 \x01(\bR\breserved2\xc0\x01\n" +
	"\fStockService\x120\n" +
	"\bGetStock\x12\x16.stock.GetStockRequest\x1a\f.stock.Stock\x12>\n" +
	"\fReserveStock\x12\x1a.stock.ReserveStockRequest\x1a\x12.stock.Reservation\x12>\n" +
	"\fReleaseStock\x12\x1a.stock.ReleaseStockRequest\x1a\x12.stock.ReservationB1Z/github.com/wypwzc/go-mall/apps/stock/pb;stockpbb\x06proto3"

var (
	file_apps_stock_stock_proto_rawDescOnce sync.Once
	file_apps_stock_stock_proto_rawDescData []byte
)

func file_apps_stock_stock_proto_rawDescGZIP() []byte {
	file_apps_stock_stock_proto_rawDescOnce.Do(func() {
		file_apps_stock_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_stock_stock_proto_rawDesc), len(file_apps_stock_stock_proto_rawDesc)))
	})
	return file_apps_stock_stock_proto_rawDescData
}

var file_apps_stock_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apps_stock_stock_proto_goTypes = []any{
	(*GetStockRequest)(nil),     // 0: stock.GetStockRequest
	(*Stock)(nil),               // 1: stock.Stock
	(*ReserveStockRequest)(nil), // 2: stock.ReserveStockRequest
	(*ReleaseStockRequest)(nil), // 3: stock.ReleaseStockRequest
	(*Reservation)(nil),         // 4: stock.Reservation
}
var file_apps_stock_stock_proto_depIdxs = []int32{
	0, // 0: stock.StockService.GetStock:input_type -> stock.GetStockRequest
	2, // 1: stock.StockService.ReserveStock:input_type -> stock.ReserveStockRequest
	3, // 2: stock.StockService.ReleaseStock:input_type -> stock.ReleaseStockRequest
	1, // 3: stock.StockService.GetStock:output_type -> stock.Stock
	4, // 4: stock.StockService.ReserveStock:output_type -> stock.Reservation
	4, // 5: stock.StockService.ReleaseStock:output_type -> stock.Reservation
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_stock_stock_proto_init() }
func file_apps_stock_stock_proto_init() {
	if File_apps_stock_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_stock_stock_proto_rawDesc), len(file_apps_stock_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_stock_stock_proto_goTypes,
		DependencyIndexes: file_apps_stock_stock_proto_depIdxs,
		MessageInfos:      file_apps_stock_stock_proto_msgTypes,
	}.Build()
	File_apps_stock_stock_proto = out.File
	file_apps_stock_stock_proto_goTypes = nil
	file_apps_stock_stock_proto_depIdxs = nil
}
